spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true